name: sticky_notes
description: A draggable, interactive sticky note widget for Flutter.
version: 1.0.1
repository: "https://github.com/mis177/sticky-notes"
homepage: https://github.com/mis177/sticky-notes
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

platforms:
  android:
  ios:
  web:
  windows:

screenshots:
- description: 'Example code in action'
  path: example/screenshots/usage2.gif

flutter:

